version: "3.0"
services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: application
    container_name: application
    volumes:
      - ../data/textos.csv:/app/textos.csv
      - ./:/app/
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - 8000:8000
    networks:
      - net

networks:
  net:
    driver: bridge